name: Benchmark

on: [push, pull_request]

jobs:
  benchmark-linux:
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Cache results.pkl
      uses: actions/cache@v3
      with:
        path: ./results.pkl
        key: results-${{ github.ref }}-${{ github.run_id }}
        restore-keys: results-${{ github.ref }}-

    - name: Install dependencies
      run: |
        pacman -Syu --noconfirm
        pacman -S --noconfirm gcc git gnuplot python

    - name: Check for cached results
      run: |
        if [ -f results.pkl ]; then
          echo "Cached results.pkl found."
        else
          echo "No cached results.pkl found."
        fi

    - name: Run bench.py
      run: python bench.py -s

    - name: Archive results for Git operations
      uses: actions/upload-artifact@v3
      with:
        name: benchmark-results
        path: |
          bench*.md
          img/

  benchmark-commit:
    needs: benchmark-linux
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download benchmark results
      uses: actions/download-artifact@v3
      with:
        name: benchmark-results

    - name: Configure Git
      run: |
        git config user.name 'GitHub Actions'
        git config user.email 'actions@github.com'

    - name: Commit benchmark updates
      run: |
        git add bench*.md img/
        git commit -m "Update benchmarks and images" -a || echo "No changes to commit"
        git push
