name: Build and benchmark

on: [push, pull_request]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Update system and Install dependencies
      run: |
        pacman -Syu --noconfirm
        pacman -S --noconfirm base-devel vim

    - name: Build
      run: make

    - name: Test
      run: make test

  build-macos:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build
      run: make

    - name: Test
      run: make test

  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup environment
        run: |
          choco install make mingw

      - name: Build
        run: make CC=gcc

  benchmark-linux:
    needs: build-linux
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Cache benchmark results
      uses: actions/cache@v4
      with:
        path: ./results.pkl
        key: results-${{ github.ref }}-${{ github.run_id }}
        restore-keys: results-${{ github.ref }}-

    - name: Install dependencies
      run: |
        pacman -Syu --noconfirm
        pacman -S --noconfirm gcc git gnuplot python

    - name: Check for cached results
      run: |
        if [ -f results.pkl ]; then
          echo "Cached results.pkl found."
        else
          echo "No cached results.pkl found."
        fi

    - name: Run bench.py
      run: python bench.py -s

    - name: Archive results for Git operations
      uses: actions/upload-artifact@v4
      with:
        name: benchmark-results
        path: |
          bench*.md
          img/

  benchmark-commit:
    needs: benchmark-linux
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download benchmark results
      uses: actions/download-artifact@v4
      with:
        name: benchmark-results

    - name: Configure Git
      run: |
        git config user.name 'GitHub Actions'
        git config user.email 'actions@github.com'

    - name: Commit benchmark updates
      run: |
        git add bench*.md img/
        git commit -m "Update benchmarks and images" -a || echo "No changes to commit"
        git push
