name: C/C++ CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: archlinux:latest

    steps:
    - uses: actions/checkout@v4

    - name: Update system and Install dependencies
      run: |
        sudo pacman -Syu --noconfirm
        sudo pacman -S --noconfirm gcc vim

    - name: Build
      run: make

    - name: Test
      run: make test
